# Generated by Django 4.1.5 on 2023-02-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_porject_vote_ratio_porject_vote_total_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('1', 'Bad'), ('2', 'Not Bad'), ('3', 'Not Good'), ('4', 'Good'), ('5', 'Perfect')], max_length=200),
        ),
    ]
