# Generated by Django 4.1.5 on 2023-02-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_porject_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porject',
            options={'ordering': ['-vote_ratio', '-vote_total']},
        ),
    ]
